#!/bin/sh
set -ex

PREREQ="network"
prereqs()
{
   echo "$PREREQ"
}

case $1 in
prereqs)
   prereqs
   exit 0
   ;;
esac

. /scripts/functions
. /etc/encryptrootfs.conf
if [ ! -f "/usr/sbin/dropbear" ]; then
   panic "Dropbear binary is not available"
fi
log_file="/tmp/dropbear.log"
log_begin_msg "Starting up dropbear on $dropbear_port port. Logfile: $log_file"
/usr/sbin/dropbear -E -m -s -j -k -p "$dropbear_port" -P /tmp/dropbear.pid 2>"$log_file"
if [ $? -gt 0 ];then
    log_failure_msg "Dropbear sshd failed to start. Log:\n $(cat "$log_file")"
    #let us see what happened
    sleep "$pause_on_error"
    panic "Dropbear sshd failed to start. Log:\n $(cat "$log_file")"
else
    log_end_msg "Dropbear had started. Log: \n $(cat "$log_file")"
fi
exit 0
